replicaCount: 1

image:
  repository: jun2281/hello-rancher
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  ingressClassName:
  hosts:
    - host: ""
      paths:
        - path: /80
          pathType: Prefix
  backend:
    port: 80
  tls: []