replicaCount: 1

image:
  repository: jun2281/hello-rancher
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: ""
      paths:
        - path: /testpatch
          pathType: ImplementationSpecific
  backend:
    port: 80
  tls: []