replicaCount: 1

image:
  repository: jun2281/hello-rancher
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2   # захватываем вторую группу
  hosts:
    - host: ""                # если пусто — работает на всех хостах, лучше указать ваш домен
      paths:
        - path: /testpatch(/|$)(.*)   # регулярка: /testpatch/всё_что_далее
          pathType: ImplementationSpecific   # обязательно
  backend:
    port: 80
  tls: []